### ISSUE TITLE
[feature] coverage nestjs-signed-url with tests

### ISSUE THREAD

**Issue by tuogeniy** [atls/nestjs#159]
### С чем связан запрос на фичу?
возникла необходимость в покрытии кода тестами

### Расскажите как вы это себе видите
1. Создать папку tests
2. Протестировать код
- протестировать публичные методы единственного сервиса https://github.com/Atlantis-Lab/nestjs/blob/master/packages/nestjs-signed-url/src/services/signed-url.service.ts
- протестировать публичные методы модуля https://github.com/Atlantis-Lab/nestjs/blob/master/packages/nestjs-signed-url/src/module.ts

**Comment by NavruzJn** [comment]
Необходимо покрыть тестами две функции
1. generateWriteUrl
2. generateReadUrl

Для теста надо создать тестовый модуль с помощью библиотеки @nestjs/testing
