### ISSUE TITLE
Обновление зависимостей `keto`

### ISSUE THREAD

**Issue by SlumberyDude** [atls/nestjs#266]
### С чем связан запрос на фичу?

Обновление зависимостей в модуле `keto`

### Расскажите как вы это себе видите

Обновить и зафиксировать версии пакета `@atls/nestjs-keto` до максимально возможных таким образом, чтобы ничего не ломалось, а именно проходили команды **критерия готовности**.

### Исключения:
Зависимости `typescript`, `typeorm` обновлять не нужно.

Если ломаются тесты и это связанно с переходом `NestJs` с версии `8` на `10`, и проблема не на поверхности (не фиксится заменой в тесте, например, метода `.asyncListen` на `.listen`), то пакеты, начинающиеся с `@nestjs/...` обновлять не выше мажорной `8`.

### Definition of done (критерий готовности)

Проходят без ошибок команды:
- `yarn install`
- `yarn check`
- `yarn test unit`

Если в пакете есть скрипты `build` и `prepack`, то они тоже должны проходить без ошибок.

### Приложите пример реализаций

https://classic.yarnpkg.com/lang/en/docs/cli/workspace/
`yarn workspace <workspace> add <package@1.2.3> <keys>`

### Приложите материалы задачи

Можете посмотреть закрытые PR и issue по теме обновления зависимостей

**Comment by IgorSmugalov** [comment]
@SlumberyDude 
Пакет [@oryd/keto-client](https://www.npmjs.com/package/@oryd/keto-client) обновился, но он Deprecated , актуаленый [@ory/keto-client](https://www.npmjs.com/package/@ory/keto-client) имеет другой api, поискал что-то по этому поводу в документации - ничего не нашел

**Comment by SlumberyDude** [comment]
@IgorSmugalov Думаю на новый api точно не надо переходить в рамках обновления зависимостей. Если с deprecated последней версии все работает, то ок.

**Comment by IgorSmugalov** [comment]
@SlumberyDude

- Все пакеты обновлены до последних версий
- Типизировал Metadata для KetoAccessControlGuard: без этого не проходили тайпчеки при переходе на nestjs^10

Следующие тесты проходят без ошибок:
- yarn install
- yarn check
- yarn test unit
- build
- prepack

Примечания:

- apollo-server-core - обновлен, но в статусе deprecated

**Comment by SlumberyDude** [comment]
@IgorSmugalov Сделай PR. Назови ветку в соответствии с конвенцией, то есть что-то типа `feat/keto-update-deps`. Потом если в PR все чеки пройдут запрашивай у меня ревью
