### ISSUE TITLE
Обновление зависимостей `signed-url`

### ISSUE THREAD

**Issue by SlumberyDude** [atls/nestjs#269]
### С чем связан запрос на фичу?

Обновление зависимостей в модуле `signed-url`

### Расскажите как вы это себе видите

Обновить и зафиксировать версии пакета `@atlantis-lab/nestjs-signed-url` до максимально возможных таким образом, чтобы ничего не ломалось, а именно проходили команды **критерия готовности**.

### Исключения:
Зависимости `typescript`, `typeorm` обновлять не нужно.

Если ломаются тесты и это связанно с переходом `NestJs` с версии `8` на `10`, и проблема не на поверхности (не фиксится заменой в тесте, например, метода `.asyncListen` на `.listen`), то пакеты, начинающиеся с `@nestjs/...` обновлять не выше мажорной `8`.

### Definition of done (критерий готовности)

Проходят без ошибок команды:
- `yarn install`
- `yarn check`
- `yarn test unit`

Если в пакете есть скрипты `build` и `prepack`, то они тоже должны проходить без ошибок.

### Приложите пример реализаций

https://classic.yarnpkg.com/lang/en/docs/cli/workspace/
`yarn workspace <workspace> add <package@1.2.3> <keys>`

### Приложите материалы задачи

Можете посмотреть закрытые PR и issue по теме обновления зависимостей

**Comment by ArtemMakhaydinov** [comment]
@SlumberyDude 
В signed-url "typescript": "4.1.3"
В корневом package.json "typescript": "4.5.5" в resolution
В папке проекта подогнать TS под залоченную версию?

**Comment by SlumberyDude** [comment]
@ArtemMakhaydinov Если не будет ошибок то да, можно повысить до 4.5.5. Ну вроде их быть не должно, залоченная ведь работает
