### ISSUE TITLE
Обновление зависимостей `typesense`

### ISSUE THREAD

**Issue by SlumberyDude** [atls/nestjs#271]
### С чем связан запрос на фичу?

Обновление зависимостей в модуле `typesense`

### Расскажите как вы это себе видите

Обновить и зафиксировать версии пакета `@atls/nestjs-typesense` до максимально возможных таким образом, чтобы ничего не ломалось, а именно проходили команды **критерия готовности**.

### Исключения:
Зависимости `typescript`, `typeorm` обновлять не нужно.

Если ломаются тесты и это связанно с переходом `NestJs` с версии `8` на `10`, и проблема не на поверхности (не фиксится заменой в тесте, например, метода `.asyncListen` на `.listen`), то пакеты, начинающиеся с `@nestjs/...` обновлять не выше мажорной `8`.

### Definition of done (критерий готовности)

Проходят без ошибок команды:
- `yarn install`
- `yarn check`
- `yarn test unit`

Если в пакете есть скрипты `build` и `prepack`, то они тоже должны проходить без ошибок.

### Приложите пример реализаций

https://classic.yarnpkg.com/lang/en/docs/cli/workspace/
`yarn workspace <workspace> add <package@1.2.3> <keys>`

### Приложите материалы задачи

Можете посмотреть закрытые PR и issue по теме обновления зависимостей

**Comment by RimidalU** [comment]
@TorinAsakura 
Обновлены все зависимости за исключением:

#### 1.  typesense обновлёна до 0.15.0 (latest 1.7.1). Это предыдущая перед 1.0.0.
При использовании версий начиная с 1.0 возникают ошибки с типами, возможно потребуется добавить проверку на undefined, так так либа была полностью переписанна на ts, причем другим разработчиком. 
Если же выше листать по версиям, то поменялся API.

#### 2.  decamelize 5.0.0 (latest 6.0.0). 
Либа в версии 6.0.0 переписана на ES6.
