### ISSUE TITLE
Адаптер `keto-grpc`

### ISSUE THREAD

**Issue by Nelfimov** [atls/nestjs#289]
### С чем связан запрос на фичу?

Необходимо добавить адаптер и гард для использования `keto-grpc-client`

### Расскажите как вы это себе видите

- [x] используем `@ory/keto-grpc-client`
- [x] необходимы клиенты для
  - [x] чтения
  - [x] записи
- [x] УРЛ для отправки запросов должен быть кастомизируем
- [x] посмотреть в каком формате передавать тупли
- [x] тесты

### Definition of done (критерий готовности)

Тесты проходят, пакет предоставляет гард, есть кастомизация УРЛа запросов

**Comment by Nelfimov** [comment]
@SlumberyDude посмотри пожалуйста тест в `@atls/grpc-keto` - не могу понять почему падает

**Comment by SlumberyDude** [comment]
@Nelfimov Нашел [вот тут](https://github.com/nestjs/nest/issues/9545#issuecomment-1120504449) похожий кейс, что глобальную константу нестовую не нужно экспортировать, если убрать `guardProvider` из экспортируемых переменных, то ошибки не будет. Ну или создать под гард отдельную свою константу, а не `APP_GUARD` хотя скорее всего это будет уже не то.

Наверное глобальный гард можно не экспортировать, потому что в доке написано, что они распространяются на все приложение. (вот непонятно, где это приложение заканчивается) https://docs.nestjs.com/guards и будут работать для всего приложения наверное

> Global guards are used across the whole application, for every controller and every route handler. In terms of dependency injection, global guards registered from outside of any module

> When using this approach to perform dependency injection for the guard, note that regardless of the module where this construction is employed, the guard is, in fact, global.

**Comment by Nelfimov** [comment]
@SlumberyDude столкнулся с другой проблемой - в интеграционном тесте `KetoGuard` не видит свою зависимость `KetoReadClientService`, хотя она поставляется модулем.

Воспроизведение: `yarn test integration client-read.test`

```ts
Nest can't resolve dependencies of the KetoGuard (Reflector, ?). Please make sure that the argument dependency at index [1] is available in the KetoIntegrationModule context.

    Potential solutions:
    - Is KetoIntegrationModule a valid NestJS module?
    - If dependency is a provider, is it part of the current KetoIntegrationModule?
    - If dependency is exported from a separate @Module, is that module imported within KetoIntegrationModule?
      @Module({
        imports: [ /* the Module containing dependency */ ]
      })
```

Сам тест находится тут: `/packages/grpc-keto/integration/test`

**Comment by TorinAsakura** [comment]
> @SlumberyDude столкнулся с другой проблемой - в интеграционном тесте `KetoGuard` не видит свою зависимость `KetoReadClientService`, хотя она поставляется модулем.
> 
> Воспроизведение: `yarn test integration client-read.test`
> 
> ```ts
> Nest can't resolve dependencies of the KetoGuard (Reflector, ?). Please make sure that the argument dependency at index [1] is available in the KetoIntegrationModule context.
> 
>     Potential solutions:
>     - Is KetoIntegrationModule a valid NestJS module?
>     - If dependency is a provider, is it part of the current KetoIntegrationModule?
>     - If dependency is exported from a separate @Module, is that module imported within KetoIntegrationModule?
>       @Module({
>         imports: [ /* the Module containing dependency */ ]
>       })
> ```
> 
> Сам тест находится тут: `/packages/grpc-keto/integration/test`

пересобери ярн

**Comment by Nelfimov** [comment]
Снос `yarn.lock` и пересборка не помогли. 

После этого повалились все тайпчеки по репе из-за нефиксированных версий.

**Comment by TorinAsakura** [comment]
@Nelfimov папку кеш, а не ярн лок

**Comment by Nelfimov** [comment]
не помогло

**Comment by SlumberyDude** [comment]
@Nelfimov Проблема в том, что из модуля `KetoModule`  гард экспортируется в виде
```ts
{
    provide: KETO_GUARD,
    useFactory: (reflector: Reflector, ketoReadClient: KetoReadClientService) =>
      new KetoGuard(reflector, ketoReadClient),
    inject: [KETO_READ_CLIENT],
},
```

То есть он привязывается к токену-константе `KETO_GUARD`

А потом уже в контроллере клиент (у нас `KetoIntegrationController`) использует `@UseGuards(KetoGuard)` что не прокатывает потому что экспортируется не `KetoGuard`, а `KETO_GUARD`. Вот ищу как это обойти, пока что не могу загуглить как экспортированный в виде токена гард потом использовать в декораторе `@UseGuards`. Обычно эти экспортированные в виде токенов-констант провайдеры инжектят в другие провайдеры через `@Inject(OTHER_PROVIDER_TOKEN) otherProvider: OtherProvider`, но тут другой случай.

**Comment by SlumberyDude** [comment]
@Nelfimov Если явно добавить `CheckServiceClient, KetoReadClientService, KetoGuard` в список провайдеров в кето модуль, то вроде ошибка импорта чинится, 
```
return {
      global: options?.global ?? true,
      module: KetoModule,
      providers: [...optionsProvider, ...exportsProvider, CheckServiceClient, KetoReadClientService, KetoGuard],
      exports: [...exportsProvider]
}
```

Другого способа пока что не нашел

**Comment by Nelfimov** [comment]
@SlumberyDude сделал рефактор кода, добавил много чего в провайдеры. Сейчас ошибка такая:

`Nest can't resolve dependencies of the KetoCheckClientService (?). Please make sure that the argument dependency at index [0] is available in the KetoModule context.`

Речь о вот этом провайдере:

```ts
export class KetoCheckClientService extends CheckServiceClient {
  constructor(@Inject(KETO_MODULE_OPTIONS) private readonly options: KetoModuleOptions) {
    super(options.read, options.credentials)
  }
}
```

И что странно, `KETO_MODULE_OPTIONS` он якобы не находит, хотя они есть в модуле:

```ts
export const createKetoOptionsProvider = (options: KetoModuleOptions): Provider[] => [
  {
    provide: KETO_MODULE_OPTIONS,
    useValue: options,
  },
]
```

Можешь плиз посмотреть?

**Comment by SlumberyDude** [comment]
@Nelfimov Исправил провайдеры на вот это

<details>

```ts
export const createKetoExportsProvider = (): Provider[] => [
  {
    provide: KETO_CHECK_CLIENT,
    // useClass: KetoCheckClientService,
    useFactory: (options: KetoModuleOptions) =>
      new KetoCheckClientService(options),
    inject: [KETO_MODULE_OPTIONS]
  },
  {
    provide: KETO_WRITE_NATIVE_CLIENT,
    // useClass: KetoWriteNativeClientService,
    useFactory: (options: KetoModuleOptions) =>
      new KetoWriteNativeClientService(options),
    inject: [KETO_MODULE_OPTIONS]
  },

  {
    provide: KETO_READ_CLIENT,
    // useClass: KetoReadClientService,
    useFactory: (checkClientService: KetoCheckClientService) =>
      new KetoReadClientService(checkClientService),
    inject: [KETO_WRITE_NATIVE_CLIENT]
  },
  {
    provide: KETO_WRITE_CLIENT,
    // useClass: KetoWriteClientService,
    useFactory: (ketoWriteNativeClientService: KetoWriteNativeClientService) =>
      new KetoWriteClientService(ketoWriteNativeClientService),
    inject: [KETO_CHECK_CLIENT]
  },
  {
    provide: KETO_GUARD,
    useFactory: (reflector: Reflector, ketoReadClient: KetoReadClientService) =>
      new KetoGuard(reflector, ketoReadClient),
    inject: [KETO_READ_CLIENT],
  },
]

```

</details>

Прокатило, чтобы `yarn test integration grpc-keto` перестал выдавать ошибки связанные с зависимостями, но в решении я не уверен.

**Comment by Nelfimov** [comment]
Теперь будто прошлись по кругу и вернулись обратно:

`Nest can't resolve dependencies of the KetoGuard (Reflector, ?). Please make sure that the argument dependency at index [1] is available in the KetoIntegrationModule context.`

```ts
@Module({
  imports: [
    KetoModule.register({
      read: 'http://localhost:4466',
      write: 'http://localhost:4467',
    }),
  ],
  controllers: [KetoIntegrationController],
})
export class KetoIntegrationModule {}
```

```ts
@Injectable()
export class KetoGuard implements CanActivate {
  constructor(
    private readonly reflector: Reflector,
    @Inject(KETO_READ_CLIENT) private readonly ketoReadClient: KetoReadClientService
  ) {}
...
```

**Comment by SlumberyDude** [comment]
@Nelfimov Может действительно было правильно (как изначально было) сделать `guard` провайдер как-то вроде 

```ts
{
    provide: APP_GUARD,
    useFactory: (reflector: Reflector, ketoReadClient: KetoReadClientService) =>
      new KetoGuard(reflector, ketoReadClient),
    inject: [KETO_READ_CLIENT],
  }
```
Чтобы сделать его глобальным. Тогда вроде его не нужно экспортировать, а только записать в провайдеры. И убрать `@UseGuards(KetoGuard)` из контроллера `KetoIntegrationController` (потому что по идее глобальный гард должен работать и так - то есть без декоратора).

**Comment by Nelfimov** [comment]
Проверю, однако цель у этого адаптера сделать локальный гард чтобы покрывать только часть контроллера.

**Comment by SlumberyDude** [comment]
@Nelfimov А как в прошлый раз получилось преодолеть ошибку, когда такая де было? Ты говоришь мы сделали круг.

**Comment by Nelfimov** [comment]
Решил проблему - гарды нельзя экспортировать, иначе они не увидят скоуп модуля куда импортируются. Поэтому просто убрал гард из экспортируемых провайдеров. 

Тут подробнее: https://github.com/nestjs/nest/issues/3856#issuecomment-575925668

**Comment by SlumberyDude** [comment]
@Nelfimov А если их не экспортировать, то тогда как ими пользоваться?

**Comment by Nelfimov** [comment]
Брать напрямую из пакета и использовать в UseGuards
